"""
AI Layer — LangChain + Groq setup
===================================
Initialises the ChatGroq LLM and prompt templates used by the explanation
and fallback chains.

NOTE: This module is deliberately isolated. If GROQ_API_KEY is not set,
it returns None gracefully so the rest of the pipeline still works.
"""
from __future__ import annotations

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate

from app.config import settings


def get_llm() -> ChatGroq | None:
    """Return a configured ChatGroq instance, or None if no API key."""
    if not settings.groq_api_key:
        return None
    return ChatGroq(
        api_key=settings.groq_api_key,
        model=settings.groq_model,
        temperature=0.3,
        max_tokens=256,
    )


# --- Explanation prompt template ---
EXPLAIN_PROMPT = ChatPromptTemplate.from_messages([
    ("system",
     "You are a concise technical assistant for a compiler-design project. "
     "Given a test case generated by symbolic execution, write ONE sentence "
     "explaining what execution path it covers and why it is important for testing. "
     "Be specific about the condition value and branch taken. "
     "Do not mention that you are an AI."),
    ("human",
     "Test case:\n"
     "- Condition: {condition_expr}\n"
     "- Branch taken: {branch_taken}\n"
     "- Input values: {input_values}\n"
     "- Expected output: {expected_output}\n"
     "- Is boundary value: {boundary_flag}\n\n"
     "Write ONE sentence explanation:"),
])


# --- Fallback prompt template (for unsupported constructs) ---
FALLBACK_PROMPT = ChatPromptTemplate.from_messages([
    ("system",
     "You are a test-case advisor for a C program analysis tool. "
     "A C code construct could not be modelled by the deterministic CFG engine. "
     "Suggest ONE plausible test case for this construct as a JSON object with keys: "
     "input_values (dict), expected_output (str), rationale (str). "
     "Respond ONLY with the JSON object, nothing else."),
    ("human",
     "Unsupported construct description: {construct_description}\n"
     "Source code context:\n{source_context}"),
])
